---
title: "Shell Scripting"
subtitle: "Spring 2016 BZAN 583"
author: "Drew Schmidt"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  beamer_presentation:
    toc: true
    keep_tex: true
    highlight: tango
    theme: "Frankfurt"
    slide_level: 2
    includes:
      in_header: include/slides_header.tex
---

```{r, echo=FALSE, message=FALSE}
library(knitr)
opts_chunk$set(cache=TRUE, fig.align="center", fig.width=5, fig.height=3)
```



##
### Today's Learning Objectives
* 



# Quick Note on Scripting

##
### Scripting in a Slide
* Just the very basics (see handout for details).
* Place your commands in a file.
* Execute `chmod +x myfile`.
* Run the script via:
    * relative path: `./myfile`
    * absolute path: `/path/to/myfile`
* The first line can be a "magic comment"
    * `#!/bin/sh`
    * `#!/bin/sh`
* Conditionals and loops are possible, but beyond scope.

##
### Variables
* Assign with `=`
* If a space occurs, put the RHS in quotes
* Reference with preceeding `$`
* Store the output of a command with "backticks" `` ` ``


##
### Example
```bash
x=something
x = something # NO!

x="something else"

echo $x

x=`ls ~ | grep D`
echo $x
```




# Getting Data

##
### 
* `wget`
* `curl`
* `sftp`


# Inspecting Data

##
### 
head/tail, grep, 

```bash
head -2 a b
```


# Summary Statistics

##
### 
wc, ...


```bash
sort -u big.txt | wc -l
```


##
### Examples
```bash
# convert csv to tsv
sed 's/,/\t/g' small.csv > small.tsv


awk 'BEGIN {FS=OFS=","} 


# sum column
awk '{ sum += $1 } END { print sum }' small.tsv

# average column
awk '{ sum += $1 } END { print sum/NR }' small.tsv


```






# Heavy Lifting

##
###

drop a column with cut

```bash
cut --complement -f 1 -d, iris.csv  | head

# in place
mv foo.csv foo.csv.old
etc.
```

##
###

combine two files with cat

##
###
remove blank+duplicate lines

##
### Join

```
City,Metro Population
Knoxville,852715
Nashville,1757912
Memphis,1341746

City,Founded
Knoxville,1791
Nashville,1779
Memphis,1819

join -t, a b
```


##
###

subset iris with grep

```bash
# histogram
tail -n +2 iris.csv | cut -d, -f 6 | sort | uniq -c


tail -n +2 iris.csv | tail -n +5 | cut -d, -f 6 | sort | uniq -c | sort -rn



tail -n +2 iris.csv | tail -n +5 | head -n -3 > newiris.csv
tail -n +2 newiris.csv | tail -n +5 | cut -d, -f 6 | sort | uniq -c | sort -rn > hist.txt
cat hist.txt
sed -i -e 's/^ *//g' -e 's/ /,/' hist.txt
cat hist.txt
sed -i '1 i\Count,Species' hist.txt
cat hist.txt
```

##
###

mention gnuplot



# Working with R

##
###
bringing smaller data back to R






