---
title: 'Homework 1: Introduction to the Shell'
output: pdf_document
---

*Due*: Feb 1, 2016 by the beginning of class.

You can use whatever shell/OS you like, but I will assume you have access to a modern GNU userland/flags, and your work will be graded accordingly.  As such, you are strongly encouraged to use your Ubuntu VM or Newton.



1. (10 pts) Explain briefly in words what the command `ls` does if you enter it into the terminal?  What about `# ls` (include the leading `#` symbol)?  Briefly, explain the difference.



2. (10 pts) For each of the following, determine if there is a difference between the pairs of commands.  If there is a difference, briefly explain why (if there is none, simply say so).
    a. `ls -ahl` and `ls -lah`
    b. `ls -ahl` and `ls -a -h -l`
    c. `ls -si` and `ls --si`



3. (10 pts) Briefly, in words, what does the following command do?

```bash
grep -iR "foo" *
```


4. (10 pts) Produce valid syntax for a command that takes the list of the first 5 files in your home directory in long listing format and writes this to a new file (overwriting if necessary) called `first5.txt`.  (Hint: `ls`, `head`, redirection+pipes.  `man` is your friend).



5. (10 pts) Using the `date` command, give valid syntax to display the alphabetic time zone abbreviation (currently "EST").
